# Generated by Django 2.0.1 on 2018-01-20 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charinst',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='CharInst',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
