# Generated by Django 2.0.1 on 2018-01-20 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0003_charinst'),
    ]

    operations = [
        migrations.AddField(
            model_name='charinst',
            name='char_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Test.Character'),
            preserve_default=False,
        ),
    ]
