# Generated by Django 2.0.1 on 2018-01-20 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0004_charinst_char_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charinst',
            old_name='char_id',
            new_name='char',
        ),
        migrations.RenameField(
            model_name='charinst',
            old_name='user_id',
            new_name='user',
        ),
    ]
