# Generated by Django 2.0.1 on 2018-01-20 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0005_auto_20180120_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.NullBooleanField(default=False)),
                ('kills', models.PositiveIntegerField(default=0)),
                ('deaths', models.PositiveIntegerField(default=0)),
                ('damage_dealt', models.PositiveIntegerField(default=0)),
                ('damage_received', models.PositiveIntegerField(default=0)),
                ('char_inst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.CharInst')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='game',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Test.GameTitle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charinst',
            name='game',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Test.GameTitle'),
            preserve_default=False,
        ),
    ]
