# Generated by Django 2.0.1 on 2018-01-20 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0006_auto_20180120_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='game',
        ),
        migrations.AddField(
            model_name='character',
            name='game',
            field=models.ManyToManyField(to='Test.GameTitle'),
        ),
        migrations.AlterField(
            model_name='charinst',
            name='char',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='Test.Character'),
        ),
        migrations.AlterField(
            model_name='charinst',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
