# Generated by Django 2.0.1 on 2018-01-20 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0007_auto_20180120_0539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charinst',
            name='game',
        ),
    ]
