# Generated by Django 2.0.1 on 2018-01-20 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0009_auto_20180120_0625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='game',
        ),
        migrations.AddField(
            model_name='character',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='Test.GameTitle'),
            preserve_default=False,
        ),
    ]
